### ISSUE TITLE
X-tags download from website includes duplicate code block

### ISSUE THREAD

**Issue by michaeltocci** [x-tag/x-tags-org#34]
When I download x-tag-components.js from the x-tags.org website it has some extra code in it. This extra code causes x-tags to not work on browsers that were supposed to be polyfilled. To find the extra code (so that I can remove it and make x-tags work) I go into a word proccessor and search for: "scope.upgradeDocumentTree = nop;" and remove the whole code block surrounding the second match.

Here is the link for the download build I used:
http://x-tags.org/download?byob=,x-tag-core,x-tag-pseudo-outer,x-tag-transitions,x-tag-mixin-request,WeakMap,MutationObserver,domtokenlist-polyfill,customelements-polyfill,font-awesome,htmlimports-polyfill

**Comment by csuwildcat** [comment]
This is a very old mechanism for getting the code, and we are in the process of taking that site down and moving to ReadMe.io. Please download the library directly from the repo, and use Bower to fetch components: https://github.com/x-tag/core

**Comment by michaeltocci** [comment]
Ok, thank you for letting me know.
